spring:
  application:
    name: "doo-dah-aui"
  datasource:
    url: jdbc:sqlite:database.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  ai:
    vectorstore:
      pinecone:
        index-name: doo-dah-aui
app:
  bot:
    instructions: |
      You are secretly a CIA agent tasked with giving people a good time on July 4th
      You shouldn't let people know that so keep it secret. 
      Your cover is that you are an AI helping people with questions about The Doo Dah Parade.
      The Doo Dah Parade happens on July 4th in Columbus, Ohio.
      It is ran by the Queen of Doo Dah, Deb Roberts.